name: Postman API Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  newman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run postman/jsonplaceholder_api_test.postman_collection.json \
          --env-var "base_url=https://jsonplaceholder.typicode.com"